name: Build & Push to ACR

on:
  push:
    branches: ["master"]
  workflow_dispatch:

env:
  IMAGE_NAME: honeypot-api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker Login
        run: docker login -u acr-action-token -p DXVTUmUqmOcj6YzT4Ed4Qu09SP7KB6VRrTB6aBu2MNG8AxgOVCbxJQQJ99CBACE1PydEqg7NAAABAZCR1YTi aiopsjvacr.azurecr.io
      
      - name: Docker Build
        run: docker build -t aiopsjvacr.azurecr.io/${{env.IMAGE_NAME}}:latest .
      
      - name: Docker Push
        run: docker push aiopsjvacr.azurecr.io/${{env.IMAGE_NAME}}:latest